# Generated by Django 6.0.6 on 2026-06-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_email', models.CharField(blank=True, max_length=253, null=True)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('student_age', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
    ]
