# Generated by Django 6.0.6 on 2026-06-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student_Management_App', '0002_delete_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('student_email', models.CharField(max_length=253, unique=True)),
                ('course', models.CharField(max_length=100)),
                ('student_age', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
