# Generated by Django 6.0.6 on 2026-06-19 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Management_App', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
