# Generated by Django 6.0.6 on 2026-06-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student_Management_App', '0006_delete_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_email', models.EmailField(blank=True, max_length=253, null=True, unique=True)),
                ('course', models.CharField(max_length=100)),
                ('student_age', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
    ]
